### ISSUE TITLE
ChaCha20-Poly1305 as in RFC 7539

### ISSUE THREAD

**Issue by cfcs** [abeaumont/ocaml-chacha#1]
Hello!

I currently need `ChaCha20-Poly1305` as defined in [RFC 7539](https://tools.ietf.org/html/rfc7539), which is used in the [Noise protocol framework](http://noiseprotocol.org/).

I adapted poly1305 from the [WireGuard sources](https://github.com/WireGuard/WireGuard/tree/master/src/crypto) and fitted OCaml bindings based on your `salsa20-core` library - that is available here: https://github.com/cfcs/ocaml-poly1305

The WireGuard repository also has a ChaCha20 implementation if that is of any use. The code runs in kernel-mode, which means it has fewer ties to libc than the regular userland implementations, and may be easier to port for MirageOS use.
I'm not sure if you want to merge poly1305 into your chacha20 library, but that could be an option.

Anyway, just a heads up on what I've been spending my time on. :-)

**Comment by abeaumont** [comment]
Thanks @cfcs for the info and pointers!
I think keeping poly1305 and ChaCha makes sense since ChaCha functions can be useful by themselves for different purposes, and it should be easy for the poly1305 just to plug a chacha implementation in. What do you think?
I've started working on ChaCha implementation, I'll let you know when I've something usable and we can see how both things fit together.

**Comment by cfcs** [comment]
I agree with the logical separation, but I think it may still be worth putting them in the same repository.
I think the maintenance overhead of C bindings justifies this, especially when the increased linked object size will be very small. But I don't mind having them separated either, so that's up to you.

Cool! Thank you!

**Comment by abeaumont** [comment]
Oh, I forgot to update this :man_facepalming: The implementation is already usable though.
